In [112]:
import pandas as pd
import os

In [155]:
banque = pd.read_csv("banque.csv")

In [156]:
banque

Empty DataFrame
Columns: [0]
Index: []

In [93]:
stock = {
"pains au chocolat": 500,
"croissants": 400,
"baguettes": 500,
"beignets": 200
}

In [94]:
print(stock)

{'pains au chocolat': 500, 'croissants': 400, 'baguettes': 500, 'beignets': 200}

In [95]:
def fabriquer(produit, quantite):
    stock[produit] = quantite
    return stock

In [96]:
fabriquer("cookies", 20)

{'pains au chocolat': 500,
 'croissants': 400,
 'baguettes': 500,
 'beignets': 200,
 'cookies': 20}

In [98]:
def vendre(produit, quantite, prix):
    prix_vente = 0
    stock[produit] -= quantite
    prix_vente += prix*quantite
    return(prix_vente)

In [133]:
temp_tresorerie = 0

In [139]:
temp_tresorerie += vendre("croissants", 10, 1)

In [163]:
banque = pd.DataFrame([temp_tresorerie])

In [175]:
banque

    0
0  20

In [180]:
banque

    0
0  20

In [181]:
banque.to_csv("banque.csv", header=False)